frontend:
  image:
    repository: ghcr.io/mahamedyahye/k8s-todo-app-frontend
    tag: latest
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  hpa:
    minReplicas: 1
    maxReplicas: 4
    cpuTarget: 50

backend:
  image:
    repository: ghcr.io/mahamedyahye/k8s-todo-app-backend
    tag: latest
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    minReplicas: 1
    maxReplicas: 4
    cpuTarget: 50

database:
  image: postgres:16-alpine
  storage: 5Gi
  storageClass: managed-csi

ingress:
  host: todo.example.com
  tlsSecret: todo-tls

keyVault:
  name: kv-todo-app-my01
  tenantId: 4255f132-9a38-4402-a201-822bbe543808
  clientId: 6e9cd23d-b783-4e2d-a6db-043c3452526d